.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH debcargo-package-debcraft 1  "package-debcraft " 
.SH NAME
debcargo\-package\-debcraft \- Package a Rust crate for debcraft (generates debcraft.yaml)
.SH SYNOPSIS
\fBdebcargo package\-debcraft\fR [\fB\-\-config\fR] [\fB\-\-directory\fR] [\fB\-\-copyright\-guess\-harder\fR] [\fB\-\-no\-overlay\-write\-back\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fICRATE_NAME\fR> [\fIVERSION\fR] 
.SH DESCRIPTION
Package a Rust crate for debcraft (generates debcraft.yaml)
.SH OPTIONS
.TP
\fB\-\-config\fR \fI<CONFIG>\fR
TOML file providing package\-specific options
.TP
\fB\-\-directory\fR \fI<DIRECTORY>\fR
Output directory for the package. The orig tarball is named according to Debian conventions in the parent directory of this directory
.TP
\fB\-\-copyright\-guess\-harder\fR
Guess extra values for debcraft/copyright. Might be slow
.TP
\fB\-\-no\-overlay\-write\-back\fR
Don\*(Aqt write back hint files to the overlay directory
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fICRATE_NAME\fR>
Name of the crate to package
.TP
[\fIVERSION\fR]
Version of the crate to package; may contain dependency operators. If empty string or omitted, resolves to the latest version
