.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH debcargo-deb-src-name 1  "deb-src-name " 
.SH NAME
debcargo\-deb\-src\-name \- Print the Debian package name for a crate
.SH SYNOPSIS
\fBdebcargo deb\-src\-name\fR [\fB\-h\fR|\fB\-\-help\fR] <\fICRATE_NAME\fR> [\fIVERSION\fR] 
.SH DESCRIPTION
Print the Debian package name for a crate
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fICRATE_NAME\fR>
Name of the crate to package
.TP
[\fIVERSION\fR]
Version of the crate to package; may contain dependency operators. If empty string, resolves to the latest version. If given here, i.e. not omitted then print the package name as if the config option semver_suffix was set to true
