.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH debcargo-update 1  "update " 
.SH NAME
debcargo\-update \- Update the user\*(Aqs default crates.io index, outside of a workspace
.SH SYNOPSIS
\fBdebcargo update\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Update the user\*(Aqs default crates.io index, outside of a workspace
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
