.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH debcargo-build-order 1  "build-order " 
.SH NAME
debcargo\-build\-order \- Print the transitive dependencies of a package in topological order
.SH SYNOPSIS
\fBdebcargo build\-order\fR [\fB\-\-config\-dir\fR] [\fB\-\-resolve\-type\fR] [\fB\-\-emulate\-collapse\-features\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fICRATE_NAME\fR> [\fIVERSION\fR] 
.SH DESCRIPTION
Print the transitive dependencies of a package in topological order
.SH OPTIONS
.TP
\fB\-\-config\-dir\fR=\fICONFIG_DIR\fR
Directory for configs. The config subdirectory for a given crate is looked up by their crate name and version, from more specific to less specific, e.g. <crate>\-1.2.3, then <crate>\-1.2, then <crate>\-1 and finally <crate>. The config file is read from the debian/debcargo.toml subpath of the looked\-up subdirectory
.TP
\fB\-\-resolve\-type\fR=\fIRESOLVE_TYPE\fR [default: SourceForDebianUnstable]
Resolution type
.br

.br
[\fIpossible values: \fRSourceForDebianUnstable, BinaryAllForDebianTesting]
.TP
\fB\-\-emulate\-collapse\-features\fR
Emulate resolution as if every package were built with \-\-collapse\-features
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fICRATE_NAME\fR>
Name of the crate to package
.TP
[\fIVERSION\fR]
Version of the crate to package; may contain dependency operators
