[package]
name = "debcargo"
version = "2.7.5-alpha.0"
authors = [
 "Josh Triplett <josh@joshtriplett.org>",
 "Ximin Luo <infinity0@debian.org>",
 "Vasudev Kamath <vasudev@copyninja.info>",
 "Fabian Grünbichler <debian@fabian.gruenbichler.email>",
]
license = "MIT/Apache-2.0"
repository = "https://salsa.debian.org/rust-team/debcargo"
description = "Create a Debian package from a Cargo crate."
edition = "2021"
rust-version = "1.58"

[dependencies]
ansi_term = "0.12"
anyhow = "1.0"
cargo = "0.83"
cargo-util = "0.2.14"
cargo-util-schemas = "0.6"
clap = { version = "4.5", features = ["cargo", "derive", "wrap_help"] }
chrono = "0.4.31"
env_logger = "0.10"
filetime = "0.2"
flate2 = "1"
git2 = "0.19"
glob = "0.3"
itertools = "0.13"
log = "0.4"
regex = "1.0"
semver = "1"
serde = "1"
serde_derive = "1"
tar = "0.4"
textwrap = "0.16"
tempfile = "3"
toml = "0.8"
walkdir = "2"
